// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:directorio_ist/docente.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(DocenteAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(DocenteAdapter());
  }
}
